//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCases.SampleAppServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://chanel.com/", ConfigurationName="SampleAppServiceRef.NameAppenderServiceClient")]
    public interface NameAppenderServiceClient {
        Resp NameAppenderService(Req req);

        // CODEGEN: Generating message contract since the operation NameAppenderService is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="NameAppenderService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestCases.SampleAppServiceRef.NameAppenderServiceResponse NameAppenderService(TestCases.SampleAppServiceRef.NameAppenderServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="NameAppenderService", ReplyAction="*")]
        System.Threading.Tasks.Task<TestCases.SampleAppServiceRef.NameAppenderServiceResponse> NameAppenderServiceAsync(TestCases.SampleAppServiceRef.NameAppenderServiceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CICD_Demo.Schemas.Input")]
    public partial class Req : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstNameField;
        
        private string lastNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CICD_Demo.Schemas.Output")]
    public partial class Resp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fullNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NameAppenderServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CICD_Demo.Schemas.Input", Order=0)]
        public TestCases.SampleAppServiceRef.Req Req;
        
        public NameAppenderServiceRequest() {
        }
        
        public NameAppenderServiceRequest(TestCases.SampleAppServiceRef.Req Req) {
            this.Req = Req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NameAppenderServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CICD_Demo.Schemas.Output", Order=0)]
        public TestCases.SampleAppServiceRef.Resp Resp;
        
        public NameAppenderServiceResponse() {
        }
        
        public NameAppenderServiceResponse(TestCases.SampleAppServiceRef.Resp Resp) {
            this.Resp = Resp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NameAppenderServiceClientChannel : TestCases.SampleAppServiceRef.NameAppenderServiceClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NameAppenderServiceClientClient : System.ServiceModel.ClientBase<TestCases.SampleAppServiceRef.NameAppenderServiceClient>, TestCases.SampleAppServiceRef.NameAppenderServiceClient {
        
        public NameAppenderServiceClientClient() {
        }
        
        public NameAppenderServiceClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NameAppenderServiceClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NameAppenderServiceClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NameAppenderServiceClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestCases.SampleAppServiceRef.NameAppenderServiceResponse TestCases.SampleAppServiceRef.NameAppenderServiceClient.NameAppenderService(TestCases.SampleAppServiceRef.NameAppenderServiceRequest request) {
            return base.Channel.NameAppenderService(request);
        }
        
        public TestCases.SampleAppServiceRef.Resp NameAppenderService(TestCases.SampleAppServiceRef.Req Req) {
            TestCases.SampleAppServiceRef.NameAppenderServiceRequest inValue = new TestCases.SampleAppServiceRef.NameAppenderServiceRequest();
            inValue.Req = Req;
            TestCases.SampleAppServiceRef.NameAppenderServiceResponse retVal = ((TestCases.SampleAppServiceRef.NameAppenderServiceClient)(this)).NameAppenderService(inValue);
            return retVal.Resp;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestCases.SampleAppServiceRef.NameAppenderServiceResponse> TestCases.SampleAppServiceRef.NameAppenderServiceClient.NameAppenderServiceAsync(TestCases.SampleAppServiceRef.NameAppenderServiceRequest request) {
            return base.Channel.NameAppenderServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestCases.SampleAppServiceRef.NameAppenderServiceResponse> NameAppenderServiceAsync(TestCases.SampleAppServiceRef.Req Req) {
            TestCases.SampleAppServiceRef.NameAppenderServiceRequest inValue = new TestCases.SampleAppServiceRef.NameAppenderServiceRequest();
            inValue.Req = Req;
            return ((TestCases.SampleAppServiceRef.NameAppenderServiceClient)(this)).NameAppenderServiceAsync(inValue);
        }
    }
}
